# Generated by Django 4.2.30 on 2026-06-25 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pyq_module', '0001_initial'),
        ('pdf_module', '0001_initial'),
        ('prompt_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('topic', models.CharField(max_length=512)),
                ('rag_top_k', models.IntegerField(default=5)),
                ('pyq_shots', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial (some failed)'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error_summary', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_runs', to=settings.AUTH_USER_MODEL)),
                ('model_config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.modelconfig')),
                ('pdf_contexts', models.ManyToManyField(blank=True, related_name='batch_runs', to='pdf_module.pdfcontext')),
                ('prompt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prompt_module.prompttemplate')),
                ('pyq_modules', models.ManyToManyField(blank=True, related_name='batch_runs', to='pyq_module.pyqmodule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchRunItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(max_length=8)),
                ('bloom', models.CharField(max_length=16)),
                ('marks', models.FloatField()),
                ('count', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('error_detail', models.TextField(blank=True)),
                ('batch_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='question_generation.batchrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
