# Generated by Django 4.2.30 on 2026-07-08 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrun',
            name='active_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='question_generation.batchrunitem'),
        ),
        migrations.AddField(
            model_name='batchrun',
            name='expected_questions',
            field=models.IntegerField(default=0),
        ),
    ]
