# Generated by Django 4.2.30 on 2026-07-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tokenusagelog_metadata_tokenusagelog_model_name_and_more'),
        ('question_generation', '0002_batchrun_active_item_batchrun_expected_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrun',
            name='council_enabled',
            field=models.BooleanField(default=False, help_text='When enabled, generated questions are verified by selected council models on bloom, correctness, question type, and appropriateness. Only majority-approved questions are kept.'),
        ),
        migrations.AddField(
            model_name='batchrun',
            name='council_models',
            field=models.ManyToManyField(blank=True, related_name='council_batch_runs', to='core.modelconfig'),
        ),
        migrations.AddField(
            model_name='batchrun',
            name='council_rejected_count',
            field=models.IntegerField(default=0, help_text='Questions discarded because they failed majority council approval.'),
        ),
    ]
