# Generated by Django 4.2.30 on 2026-07-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0003_batchrun_council_of_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchrun',
            name='progress_current',
            field=models.IntegerField(default=0, help_text='Questions completed so far (saved). Used for fine-grained progress UI.'),
        ),
        migrations.AddField(
            model_name='batchrun',
            name='progress_phase',
            field=models.CharField(blank=True, default='', help_text='Human-readable phase, e.g. generating 2/5 or council verifying…', max_length=64),
        ),
    ]
