# Generated by Django 4.2.30 on 2026-07-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_generation', '0004_batchrun_progress_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchrun',
            name='progress_current',
        ),
        migrations.RemoveField(
            model_name='batchrun',
            name='progress_phase',
        ),
    ]
