# Generated by Django 4.2.30 on 2026-06-25 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFContext',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('zip_path', models.FileField(upload_to='pdf_uploads/%Y/%m/')),
                ('strategy', models.CharField(choices=[('fixed_size', 'Fixed Size (tokens)'), ('sentence', 'Sentence Splitter'), ('paragraph', 'Paragraph Splitter'), ('recursive', 'Recursive Character Splitter'), ('semantic', 'Semantic Chunker')], default='fixed_size', max_length=32)),
                ('chunk_size', models.IntegerField(default=512)),
                ('chunk_overlap', models.IntegerField(default=64)),
                ('embed_model', models.CharField(max_length=128)),
                ('reranker_model', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pdf_contexts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PDFChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.CharField(max_length=512)),
                ('page_number', models.IntegerField(blank=True, null=True)),
                ('chunk_index', models.IntegerField()),
                ('text', models.TextField()),
                ('embedding', models.TextField(blank=True, null=True)),
                ('token_count', models.IntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='pdf_module.pdfcontext')),
            ],
            options={
                'ordering': ['context', 'source_file', 'chunk_index'],
                'indexes': [models.Index(fields=['context'], name='pdf_module__context_ee4085_idx')],
            },
        ),
    ]
