# Generated by Django 4.2.30 on 2026-06-28 16:54

from django.db import migrations
import pgvector.django.indexes


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0004_embedding_vector384_sql'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pdfchunk',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='pdfchunk_embedding_hnsw_idx', opclasses=['vector_l2_ops']),
        ),
    ]
