# Generated by Django 4.2.30 on 2026-07-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0005_pdfchunk_embedding_hnsw_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pdfchunk',
            name='pdfchunk_embedding_hnsw_idx',
        ),
        migrations.AddField(
            model_name='pdfcontext',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfcontext',
            name='original_filename',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='pdfchunk',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
