# Generated by Django 4.2.30 on 2026-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0007_restore_embedding_vector768'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfchunk',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
