# Generated by Django 4.2.30 on 2026-07-07 06:53

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0008_alter_pdfchunk_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
