# Generated by Django 4.2.30 on 2026-07-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0009_alter_pdfchunk_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfcontext',
            name='embedded_chunk_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfcontext',
            name='has_embedding',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pdfcontext',
            name='needs_reindex',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdfchunk',
            name='embedding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
