# Generated by Django 4.2.30 on 2026-07-14 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0011_restore_embedding_vector768'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pdfchunk',
            name='pdfchunk_embedding_hnsw_idx',
        ),
    ]
