# Generated by Django 4.2.30 on 2026-08-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_module', '0012_remove_pdfchunk_pdfchunk_embedding_hnsw_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfcontext',
            name='strategy',
            field=models.CharField(choices=[('hierarchical', 'Hierarchical (unit/section)'), ('fixed_size', 'Fixed Size (tokens)'), ('sentence', 'Sentence Splitter'), ('paragraph', 'Paragraph Splitter'), ('recursive', 'Recursive Character Splitter'), ('semantic', 'Semantic Chunker')], default='hierarchical', max_length=32),
        ),
    ]
