# Generated by Django 4.2.30 on 2026-06-25 06:14

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superuser', 'SuperUser'), ('orguser', 'OrgUser'), ('user', 'User')], default='user', max_length=32)),
                ('is_active_member', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('provider', models.CharField(max_length=64)),
                ('llm_model_id', models.CharField(max_length=128)),
                ('embed_model_id', models.CharField(blank=True, max_length=128)),
                ('reranker_model', models.CharField(blank=True, max_length=128)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2048)),
                ('api_key_env_var', models.CharField(blank=True, help_text='Name of the env-var that holds the API key (not the key itself)', max_length=128)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProvisioningQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_credit_limit', models.IntegerField(default=100000)),
                ('current_month_credits_used', models.IntegerField(default=0)),
                ('warning_threshold_percent', models.IntegerField(default=80)),
                ('is_hard_limited', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StorageQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_total_storage_gb', models.FloatField(default=5.0)),
                ('current_total_storage_gb', models.FloatField(default=0.0)),
                ('max_vector_storage_gb', models.FloatField(default=2.0)),
                ('current_vector_storage_gb', models.FloatField(default=0.0)),
                ('max_saved_pdf_zips', models.IntegerField(default=100)),
                ('current_saved_pdf_zips', models.IntegerField(default=0)),
                ('max_saved_pyq_zips', models.IntegerField(default=50)),
                ('current_saved_pyq_zips', models.IntegerField(default=0)),
                ('export_retention_days', models.IntegerField(default=90)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_rag_top_k', models.IntegerField(default=5)),
                ('default_pyq_shots', models.IntegerField(default=3)),
                ('max_pdf_upload_mb', models.IntegerField(default=100)),
                ('allow_docx_export', models.BooleanField(default=True)),
                ('allow_csv_export', models.BooleanField(default=True)),
                ('allow_json_export', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_llm_configs', models.ManyToManyField(blank=True, to='core.modelconfig')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationProvisioningPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_monthly_credits', models.IntegerField(default=100000)),
                ('default_storage_limit_gb', models.FloatField(default=5.0)),
                ('default_vector_storage_gb', models.FloatField(default=2.0)),
                ('default_pdf_zip_limit', models.IntegerField(default=20)),
                ('default_pyq_zip_limit', models.IntegerField(default=10)),
                ('default_daily_run_limit', models.IntegerField(default=20)),
                ('default_concurrent_run_limit', models.IntegerField(default=2)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_concurrent_runs', models.IntegerField(default=2)),
                ('max_generation_runs_per_day', models.IntegerField(default=20)),
                ('current_active_runs', models.IntegerField(default=0)),
                ('today_generation_runs', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='core.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
