# Generated by Django 4.2.30 on 2026-07-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tokenusagelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenusagelog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='model_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='provider',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='tokenusagelog',
            name='request_kind',
            field=models.CharField(choices=[('generation', 'Generation'), ('embedding', 'Embedding'), ('rerank', 'Rerank'), ('extraction', 'Extraction')], default='generation', max_length=16),
        ),
    ]
