# Generated by Django 4.2.30 on 2026-07-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_modelconfig_is_council_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('superuser', 'Admin'), ('orguser', 'Org Admin'), ('user', 'User')], default='user', max_length=32),
        ),
    ]
