# Generated by Django 4.2.30 on 2026-07-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_org_storage_pools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(help_text='Unique organisation username (letters, numbers, hyphens).', unique=True, verbose_name='username'),
        ),
    ]
