# Generated by Django 4.2.30 on 2026-07-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_control_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFIndexingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('fixed_size', 'Fixed Size (tokens)'), ('sentence', 'Sentence Splitter'), ('paragraph', 'Paragraph Splitter'), ('recursive', 'Recursive Character Splitter'), ('semantic', 'Semantic Chunker')], default='fixed_size', help_text='Chunking strategy applied to all new PDF uploads.', max_length=32)),
                ('chunk_size', models.IntegerField(default=512)),
                ('chunk_overlap', models.IntegerField(default=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('embed_config', models.ForeignKey(blank=True, help_text='Embedding model for indexing. Falls back to default embed id if empty.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.modelconfig')),
                ('reranker_config', models.ForeignKey(blank=True, help_text='Optional reranker model used during retrieval.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.modelconfig')),
            ],
            options={
                'verbose_name': 'PDF indexing settings',
                'verbose_name_plural': 'PDF indexing settings',
            },
        ),
    ]
