# Generated by Django 4.2.30 on 2026-08-04 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_reranker_model_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfindexingsettings',
            name='strategy',
            field=models.CharField(choices=[('hierarchical', 'Hierarchical (unit/section)'), ('fixed_size', 'Fixed Size (tokens)'), ('sentence', 'Sentence Splitter'), ('paragraph', 'Paragraph Splitter'), ('recursive', 'Recursive Character Splitter'), ('semantic', 'Semantic Chunker')], default='hierarchical', help_text='Chunking strategy applied to all new PDF uploads.', max_length=32),
        ),
    ]
