# Generated by Django 4.2.30 on 2026-08-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_pdfindexingsettings_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationsettings',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', help_text='Google Gemini API key (Admin Technical settings only).', max_length=512),
        ),
        migrations.AddField(
            model_name='generationsettings',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', help_text='OpenAI API key for GPT models (Admin Technical settings only).', max_length=512),
        ),
    ]
