# Generated by Django 4.2.30 on 2026-06-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PYQModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='pyq_uploads/%Y/%m/')),
                ('status', models.CharField(default='pending', max_length=32)),
                ('error_msg', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer'), ('FILL', 'Fill in the Blank'), ('TF', 'True / False'), ('CASE', 'Case Study'), ('NUM', 'Numerical')], max_length=8)),
                ('bloom', models.CharField(choices=[('remember', 'Remember'), ('understand', 'Understand'), ('apply', 'Apply'), ('analyse', 'Analyse'), ('evaluate', 'Evaluate'), ('create', 'Create')], max_length=16)),
                ('marks', models.FloatField()),
                ('is_generated', models.BooleanField(default=False)),
                ('question_text', models.TextField()),
                ('reference_answer', models.TextField(blank=True)),
                ('rubrics', models.JSONField(default=dict)),
                ('topic', models.CharField(blank=True, max_length=256)),
                ('options', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['pyq_module', 'topic', 'created_at'],
            },
        ),
    ]
