# Generated by Django 4.2.30 on 2026-07-07 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyq_module', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyqmodule',
            name='file_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pyqmodule',
            name='original_filename',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
