# Generated by Django 4.2.30 on 2026-07-23 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyq_module', '0005_question_review_field_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='reference_answer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_feedback',
            field=models.TextField(blank=True, default=''),
        ),
    ]
