# Generated by Django 4.2.30 on 2026-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyq_module', '0006_alter_question_reference_answer_alter_question_topic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('RTC', 'Reference to Context'), ('SHORT', 'Short Answer'), ('LONG', 'Long Answer')], max_length=8),
        ),
    ]
