# Generated by Django 4.2.30 on 2026-06-25 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('description', models.TextField(blank=True)),
                ('system_prompt', models.TextField(default="You are an expert exam question setter following Bloom's Taxonomy.\nGenerate exactly {{ count }} questions of type {{ question_type }} at\nBloom's level {{ bloom }} for the topic: {{ topic }}.\nEach question must be worth {{ marks }} marks.\n{% if context_chunks %}\nUse the following reference material:\n{{ context_chunks }}\n{% endif %}\n{% if pyq_examples %}\nModel your style on these example questions:\n{{ pyq_examples }}\n{% endif %}\nReturn a JSON array where each element has:\n  question_text, reference_answer, rubrics.\n")),
                ('user_prompt', models.TextField(default='Generate {{ count }} {{ question_type }} questions on "{{ topic }}" at\nBloom\'s {{ bloom }} level, {{ marks }} marks each.\n')),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PromptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('system_prompt', models.TextField()),
                ('user_prompt', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('saved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='prompt_module.prompttemplate')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('template', 'version')},
            },
        ),
    ]
