# Generated by Django 4.2.30 on 2026-07-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='system_prompt',
            field=models.TextField(default='You are an expert exam question setter following Bloom\'s Taxonomy.\nGenerate exactly {{ count }} questions of type {{ question_type }} at\nBloom\'s level {{ bloom }} for the topic: {{ topic }}.\nEach question must be worth {{ marks }} marks.\n{% if context_chunks %}\nUse the following reference material:\n{{ context_chunks }}\n{% endif %}\n{% if pyq_examples %}\nModel your style on these example questions:\n{{ pyq_examples }}\n{% endif %}\nReturn a JSON array with EXACTLY {{ count }} elements. Each element has:\n  question_text, reference_answer, rubrics.\nFor MCQ questions you MUST also include:\n  options: an array of exactly 4 objects, each with "label" (A/B/C/D) and "text".\n  reference_answer: the correct option label (e.g. "B") or full option text.\nDo not prefix question_text with "[MCQ]".\nThe array length must equal {{ count }} — no more, no less.\n'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='user_prompt',
            field=models.TextField(default='Generate {{ count }} {{ question_type }} questions on "{{ topic }}" at\nBloom\'s {{ bloom }} level, {{ marks }} marks each.\n{% if question_type == \'MCQ\' %}\nEach MCQ must have exactly 4 labelled options (A, B, C, D) and a clear correct answer.\n{% endif %}\n'),
        ),
    ]
