# Generated by Django 4.2.30 on 2026-07-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_module', '0002_alter_prompttemplate_system_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompttemplate',
            name='system_prompt',
            field=models.TextField(default='You are an expert exam question setter following Bloom\'s Taxonomy.\nGenerate exactly {{ count }} questions of type {{ question_type }} at\nBloom\'s level {{ bloom }}. Each question must be worth {{ marks }} marks.\n{% if context_chunks %}\nIMPORTANT: Base every question ONLY on the reference material below.\nQuestions must be answerable from that material alone.\nThe topic label "{{ topic }}" is for batch organization only — do NOT quote it in questions,\ndo NOT treat it as a vocabulary term, acronym, or concept to define, and do NOT ask whether\nit is a real technical term. Never invent facts about the topic string itself.\n\nReference material:\n{{ context_chunks }}\n{% else %}\nGenerate questions for the subject area: {{ topic }}.\n{% endif %}\n{% if pyq_examples %}\nMatch the difficulty, style, and format of these example questions (use new content, not copies):\n{{ pyq_examples }}\n{% endif %}\nReturn a JSON array with EXACTLY {{ count }} elements. Each element has:\n  question_text, reference_answer, rubrics.\nFor MCQ questions you MUST also include:\n  options: an array of exactly 4 objects, each with "label" (A/B/C/D) and "text".\n  reference_answer: the correct option label (e.g. "B") or full option text.\nDo not prefix question_text with "[MCQ]".\nThe array length must equal {{ count }} — no more, no less.\n'),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='user_prompt',
            field=models.TextField(default='{% if context_chunks %}\nGenerate {{ count }} {{ question_type }} question(s) from the reference material\nat Bloom\'s {{ bloom }} level, {{ marks }} marks each.\n{% if topic %}Loose theme (optional, do not quote verbatim): {{ topic }}.{% endif %}\n{% else %}\nGenerate {{ count }} {{ question_type }} question(s) on "{{ topic }}"\nat Bloom\'s {{ bloom }} level, {{ marks }} marks each.\n{% endif %}\n{% if question_type == \'MCQ\' %}\nEach MCQ must have exactly 4 labelled options (A, B, C, D) and a clear correct answer.\n{% endif %}\n'),
        ),
    ]
