# Generated by Django 4.2.30 on 2026-07-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prompt_module', '0003_alter_prompttemplate_system_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompttemplate',
            name='topic_grounding',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='system_prompt',
            field=models.TextField(default="You are an expert exam question setter following Bloom's Taxonomy.\nGenerate exactly {{ count }} questions of type {{ question_type }} at\nBloom's level {{ bloom }} for the topic: {{ topic }}.\nEach question must be worth {{ marks }} marks.\n{% if context_chunks %}\nUse the following reference material:\n{{ context_chunks }}\n{% endif %}\n{% if pyq_examples %}\nModel your style on these example questions:\n{{ pyq_examples }}\n{% endif %}\nReturn a JSON array where each element has:\n  question_text, reference_answer, rubrics.\n"),
        ),
        migrations.AlterField(
            model_name='prompttemplate',
            name='user_prompt',
            field=models.TextField(default='Generate {{ count }} {{ question_type }} questions on "{{ topic }}" at\nBloom\'s {{ bloom }} level, {{ marks }} marks each.\n'),
        ),
    ]
